### PR TITLE
⚡ Global improvements in the code and some fixes

### LINKED ISSUE #160: Doc error
Thers a ) missing [here](https://discord-giveaways.js.org/GiveawaysManager.html#event:giveawayReactionAdded) 
image
And [here](https://discord-giveaways.js.org/GiveawaysManager.html#event:giveawayReactionRemoved), single quotes must be double quotes or escape the single quote of "That's"
image

### PR DESCRIPTION
**Pull request by Nico105**
Fixes #160
Adds solution of #175
Fixes some spelling/grammar "mistakes" and typos _beautifying_ ✨
The `giveawayEnded` event should only be emitted after a giveaway has actually ended

Thoughts?

### CODE REVIEW

File: src/Manager.js [hunk 1]
```diff
@@ -488,43 +494,45 @@ class GiveawaysManager extends EventEmitter {
  * @param {Discord.MessageReaction} reaction The reaction to enter the giveaway
  *
  * @example
- * // This can be used to add features like removing the user reaction
+ * // This can be used to add features like removing reactions of members when they do not have a specific role (aka giveaway requirements). Best used with the `exemptMembers` property of the giveaways. 
  * manager.on('giveawayReactionAdded', (giveaway, member, reaction) => {
- *     if (!member.roles.cache.get('123456789'){
+ *     if (!member.roles.cache.get('123456789')) {
```
Comment (Nico105) [inline src/Manager.js:499]: #160

File: src/Manager.js [hunk 2]
```diff
@@ -488,43 +494,45 @@ class GiveawaysManager extends EventEmitter {
...
  * @event GiveawaysManager#giveawayReactionRemoved
  * @param {Giveaway} giveaway The giveaway instance
  * @param {Discord.GuildMember} member The member who remove their reaction giveaway
  * @param {Discord.MessageReaction} reaction The reaction to enter the giveaway
  *
  * @example
+ * // This can be used to add features such as a member-left-giveaway message in DM
  * manager.on('giveawayReactionRemoved', (giveaway, member, reaction) => {
- *      return member.send('That's sad, you won\'t be able to win the super cookie!');
+ *      return member.send('That\'s sad, you won\'t be able to win the super cookie!');
```
Comment (Nico105) [inline src/Manager.js:516]: #160

File: README.md [hunk 3]
```diff
@@ -65,16 +65,16 @@ client.login(settings.token);
...
--   **client**: the discord client (your discord bot instance)
--   **options.storage**: the json file that will be used to store giveaways
--   **options.updateCountdownEvery**: the number of milliseconds it will take to update the timers
--   **options.endedGiveawaysLifetime**: the number of milliseconds that a giveaway has been ended after which it can get delted from the DB
--   **options.hasGuildMembersIntent**: whether the bot has access to the GUILD_MEMBERS intent. It works without, but it will be faster with
--   **options.default.botsCanWin**: whether the bots can win a giveaway
+-   **client**: the discord client (your discord bot instance).
+-   **options.storage**: the json file that will be used to store giveaways.
+-   **options.updateCountdownEvery**: the number of milliseconds it will take to update the timers.
+-   **options.endedGiveawaysLifetime**: the number of milliseconds that giveaways have been ended after which they can get deleted from the DB.
```
Comment (Androz2091) [inline README.md:71]:
```suggestion
-   **options.endedGiveawaysLifetime**: duration for which the ended giveaways remain in the database after they are ended.
```
Maybe this is clearer?

File: README.md [hunk 4]
```diff
@@ -183,7 +183,7 @@ client.on('message', (message) => {
 **options.newWinnerCount**: the new number of winners.  
 **options.newPrize**: the new prize.  
 **options.addTime**: the number of milliseconds to add to the giveaway duration.  
-**options.setEndTimestamp**: the timestamp of the new end date. `Date.now()+1000`.
+**options.setEndTimestamp**: the timestamp of the new end date. `Date.now() + 1000`.
```
Comment (Androz2091) [inline README.md:186]:
```suggestion
**options.setEndTimestamp**: the timestamp of the new end date. (for example, for the giveaway to be ended in 1 hour, set it to `Date.now() + 60000`).
```
btw, we could change this to the following? Is it clearer?

**Review by Androz2091 — APPROVED** [review]
Thank you 👍

File: src/Manager.js [hunk 5]
```diff
@@ -488,43 +494,45 @@ class GiveawaysManager extends EventEmitter {
  * @param {Discord.MessageReaction} reaction The reaction to enter the giveaway
  *
  * @example
- * // This can be used to add features like removing the user reaction
+ * // This can be used to add features like removing reactions of members when they do not have a specific role (aka giveaway requirements). Best used with the `exemptMembers` property of the giveaways.
```
Comment (Androz2091) [inline src/Manager.js:497]:
```suggestion
 * // This can be used to add features like removing reactions of members when they do not have a specific role (such as giveaway requirements). Best used with the `exemptMembers` property of the giveaways. 
```
